---
name: Plugin Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: polaris version
